//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypesToSuggestion
    {
        public int ServiceTypeToSuggestionID { get; set; }
        public int ServiceTypeListID { get; set; }
        public int SuggestionID { get; set; }
    
        public virtual ServiceTypeList ServiceTypeList { get; set; }
        public virtual Suggestion Suggestion { get; set; }
    }
}
