//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suggestion()
        {
            this.ServiceTypesToSuggestions = new HashSet<ServiceTypesToSuggestion>();
            this.bookedDates = new HashSet<bookedDate>();
        }
    
        public int SuggestionID { get; set; }
        public string SuggestionTitle { get; set; }
        public string SuggestionDescreotion { get; set; }
        public int AdressId { get; set; }
        public Nullable<int> ageRangeID { get; set; }
        public Nullable<int> hoursRangeID { get; set; }
        public int hostId { get; set; }
        public string gender { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ageRange ageRange { get; set; }
        public virtual Host Host { get; set; }
        public virtual HoursRange HoursRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTypesToSuggestion> ServiceTypesToSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookedDate> bookedDates { get; set; }
    }
}
