//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler
    {
        public int TravelerID { get; set; }
        public string TravelerName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string gender { get; set; }
    
        public virtual User User { get; set; }
    }
}
